Repository hassio-addons/addon-unifi, pull requests merged in 2021-05, with the labels that each got.

#197 ⬆️ Upgrades add-on base image to v6.2.0
  unifi/Dockerfile
  unifi/build.json
Labels: dependencies

#198 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#199 Add translation support
  unifi/translations/en.yaml
Labels: new-feature

#200 Fix root chain
  unifi/rootfs/etc/cont-init.d/unifi.sh
Labels: bugfix

#204 ⬆ Upgrade UniFi Controller 6.2.23
  unifi/Dockerfile
Labels: dependencies, minor
