Repository hassio-addons/addon-unifi, pull requests merged in 2021-04, with the labels that each got.

#178 ⬆ Upgrade UniFi Controller version 6.1.71
  unifi/Dockerfile
Labels: dependencies, minor

#179 ⬆️ Upgrades add-on base image to v6.1.4
  unifi/Dockerfile
  unifi/build.json
Labels: dependencies

#193 Address shellcheck lint warning
  unifi/rootfs/etc/cont-init.d/unifi.sh
Labels: refactor

#194 ⬆️ Upgrades openjdk-8-jdk-headless to 8u292-b10-0ubuntu1~18.04
  unifi/Dockerfile
Labels: dependencies
