Repository hassio-addons/addon-unifi, pull requests merged in 2021-11, with the labels that each got.

#303 ⬆️ Upgrades binutils to 2.30-21ubuntu1~18.04.7
  unifi/Dockerfile
Labels: dependencies

#304 ⬆️ Upgrades libssl1.0.0 to 1.0.2n-1ubuntu5.7
  unifi/Dockerfile
Labels: dependencies

#264 snapshot -> backup
  unifi/config.json
Labels: refactor

#305 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#253 Updates to documentation after dropped 32-bit support
  README.md
  unifi/DOCS.md
Labels: documentation

#308 Migrate JSON config to YAML
  unifi/build.json
  unifi/build.yaml
  unifi/config.json
  unifi/config.yaml
Labels: refactor

#307 ⬆️ Upgrades UniFi Network Application to v6.4.54
  unifi/Dockerfile
Labels: dependencies

#309 Rebrand Controller -> Network Application
  README.md
  unifi/.README.j2
  unifi/DOCS.md
  unifi/rootfs/etc/cont-init.d/unifi.sh
  unifi/rootfs/etc/services.d/unifi/finish
  unifi/rootfs/etc/services.d/unifi/run
  unifi/translations/en.yaml
Labels: maintenance

#310 ⬆️ Upgrades add-on base image to 7.1.2
  unifi/Dockerfile
  unifi/build.yaml
Labels: dependencies

#311 Improve clarity about last log message
  unifi/rootfs/etc/services.d/unifi/run
Labels: enhancement

#291 New wording for "Inform Host" in unifi settings
  unifi/DOCS.md
Labels: documentation

#312 ⬆️ Upgrades add-on base image to 7.1.3
  unifi/Dockerfile
  unifi/build.yaml
Labels: dependencies

#315 ⬆️ Upgrades UniFi Network Application to v6.5.53
  unifi/Dockerfile
Labels: dependencies
