Repository hassio-addons/addon-unifi, pull requests merged in 2022-03, with the labels that each got.

#349 📚 Remove migrating section
  unifi/DOCS.md
Labels: documentation

#351 ⬆️ Upgrades add-on base image to 7.2.0
  unifi/Dockerfile
  unifi/build.yaml
Labels: dependencies

#352 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  .github/workflows/deploy.yaml
  unifi/build.yaml
  unifi/config.yaml
Labels: enhancement

#353 :books: Add My buttons to documentation
  unifi/DOCS.md
Labels: documentation
