Repository hassio-addons/addon-unifi, pull requests merged in 2022-09, with the labels that each got.

#382 Upgrades UniFi Network Application to 7.2.94
  unifi/Dockerfile
Labels: dependencies

#384 :ambulance: Fix missing log folders causing crash
  unifi/Dockerfile
Labels: bugfix

#385 🌎 PL translations
  unifi/translations/pl.yaml
Labels: translations
