Repository hassio-addons/addon-unifi, pull requests merged in 2022-12, with the labels that each got.

#399 ⬆️ Upgrades add-on base image to 82.0
  unifi/Dockerfile
  unifi/build.yaml
Labels: dependencies

#401 ⬆️ Upgrades UniFi Network Application to v7.3.76
  unifi/Dockerfile
Labels: dependencies, minor

#402 :stethoscope: Add healthcheck to improve HA watchdog
  unifi/Dockerfile
Labels: new-feature

#404 📚 Update docs to match latest UniFi interface
  unifi/DOCS.md
Labels: documentation
