Repository hassio-addons/addon-unifi, pull requests merged in 2023-10, with the labels that each got.

#455 Bump Unifi controller to 7.5.176 (latest)
  unifi/Dockerfile
Labels: dependencies, minor

#456 Finetune UniFi
  unifi/rootfs/etc/s6-overlay/s6-rc.d/unifi/run
Labels: performance

#457 Update to 7.5.187
  unifi/Dockerfile
Labels: dependencies
