Repository hassio-addons/addon-unifi, pull requests merged in 2024-01, with the labels that each got.

#477 :fireworks: Updates maintenance/license year to 2024
  LICENSE.md
  README.md
  unifi/.README.j2
  unifi/DOCS.md
Labels: maintenance

#478 ⬆️ Upgrades UniFi Network Application to v8.0.26
  unifi/Dockerfile
Labels: dependencies

#474 Add pt-BR translation
  unifi/translations/pt-BR.yaml
Labels: translations

#479 Fix markdown formatting in documentation
  unifi/DOCS.md
Labels: documentation
