Repository hassio-addons/addon-unifi, pull requests merged in 2024-02, with the labels that each got.

#483 Improve DOCS.md
  unifi/DOCS.md
Labels: documentation

#484 Update Network controller to version 8.0.28
  unifi/Dockerfile
Labels: dependencies

#481 Dockerfile improvements
  unifi/Dockerfile
Labels: enhancement
