Repository hassio-addons/addon-unifi, pull requests merged in 2024-03, with the labels that each got.

#491 Update base image to ubuntu-base:9.0.4
  unifi/Dockerfile
  unifi/build.yaml
  unifi/rootfs/etc/s6-overlay/s6-rc.d/init-unifi/run
Labels: refactor

#495 Update controller to 8.1.133
  unifi/Dockerfile
Labels: dependencies

#497 Revert "Update base image to ubuntu-base:9.0.4"
  unifi/Dockerfile
  unifi/build.yaml
  unifi/rootfs/etc/s6-overlay/s6-rc.d/init-unifi/run
Labels: bugfix

#496 Pin binutils to 2.34-6ubuntu1.9
  unifi/Dockerfile
Labels: dependencies
